/******************************************************
 * ArchC Resources Implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "arm_arch.H"

arm_arch::arm_arch() :
  ac_arch_dec_if<arm_parms::ac_word, arm_parms::ac_Hword>(arm_parms::AC_MAX_BUFFER),
  ac_pc("ac_pc", 0),
  MEM_port("MEM_port", 10485760U),
  MEM(*this, MEM_port),
  RB("RB"),
  R14_irq("R14_irq", 0),
  R14_fiq("R14_fiq", 0),
  R14_svc("R14_svc", 0),
  R14_abt("R14_abt", 0),
  R14_und("R14_und", 0),
  R13_irq("R13_irq", 0),
  R13_svc("R13_svc", 0),
  R13_abt("R13_abt", 0),
  R13_und("R13_und", 0),
  R13_fiq("R13_fiq", 0),
  SPSR_irq("SPSR_irq", 0),
  SPSR_fiq("SPSR_fiq", 0),
  SPSR_svc("SPSR_svc", 0),
  SPSR_abt("SPSR_abt", 0),
  SPSR_und("SPSR_und", 0),
  R12_fiq("R12_fiq", 0),
  R11_fiq("R11_fiq", 0),
  R10_fiq("R10_fiq", 0),
  R9_fiq("R9_fiq", 0),
  R8_fiq("R8_fiq", 0) {

  ac_mt_endian = arm_parms::AC_MATCH_ENDIAN;
  ac_tgt_endian = arm_parms::AC_PROC_ENDIAN;

  IM = &MEM;
  APP_MEM = &MEM;

}

