/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "arm.H"
#include  "arm_isa.cpp"

void arm::behavior() {

  unsigned ins_id;
  if (has_delayed_load) {
    APP_MEM->load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  int action = setjmp(ac_env);
  if (action == 2) return;

  for (;;) {

    arm_decode_unit::instr_dec *instr_dec;
    decode_pc = ac_pc;
    if( start_up ){
      start_up=0;
    }
    instr_dec = decode_unit->decode(decode_pc);
    ins_id = instr_dec->id;
    if( ins_id == 0 ) {
      cerr << "ArchC Error: Unidentified instruction. " << endl;
      cerr << "PC = " << hex << decode_pc << dec << endl;
      stop();
      return;
    }

    if (gdbstub && gdbstub->stop(decode_pc)) gdbstub->process_bp();

    ac_pc = decode_pc;

    ISA.cur_instr_id = ins_id;
    ISA._behavior_instruction(instr_dec->F_Type_DPI1.cond);
    switch (ins_id) {
    case 1: // Instruction and1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_and1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 2: // Instruction eor1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_eor1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 3: // Instruction sub1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_sub1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 4: // Instruction rsb1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_rsb1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 5: // Instruction add1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_add1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 6: // Instruction adc1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_adc1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 7: // Instruction sbc1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_sbc1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 8: // Instruction rsc1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_rsc1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 9: // Instruction tst1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_tst1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 10: // Instruction teq1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_teq1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 11: // Instruction cmp1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_cmp1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 12: // Instruction cmn1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_cmn1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 13: // Instruction orr1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_orr1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 14: // Instruction mov1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_mov1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 15: // Instruction bic1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_bic1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 16: // Instruction mvn1
      ISA._behavior_arm_Type_DPI1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      ISA.behavior_mvn1(instr_dec->F_Type_DPI1.cond, instr_dec->F_Type_DPI1.op, instr_dec->F_Type_DPI1.func1, instr_dec->F_Type_DPI1.s, instr_dec->F_Type_DPI1.rn, instr_dec->F_Type_DPI1.rd, instr_dec->F_Type_DPI1.shiftamount, instr_dec->F_Type_DPI1.shift, instr_dec->F_Type_DPI1.subop1, instr_dec->F_Type_DPI1.rm);
      break;
    case 17: // Instruction and2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_and2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 18: // Instruction eor2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_eor2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 19: // Instruction sub2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_sub2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 20: // Instruction rsb2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_rsb2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 21: // Instruction add2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_add2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 22: // Instruction adc2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_adc2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 23: // Instruction sbc2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_sbc2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 24: // Instruction rsc2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_rsc2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 25: // Instruction tst2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_tst2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 26: // Instruction teq2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_teq2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 27: // Instruction cmp2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_cmp2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 28: // Instruction cmn2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_cmn2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 29: // Instruction orr2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_orr2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 30: // Instruction mov2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_mov2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 31: // Instruction bic2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_bic2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 32: // Instruction mvn2
      ISA._behavior_arm_Type_DPI2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      ISA.behavior_mvn2(instr_dec->F_Type_DPI2.cond, instr_dec->F_Type_DPI2.op, instr_dec->F_Type_DPI2.func1, instr_dec->F_Type_DPI2.s, instr_dec->F_Type_DPI2.rn, instr_dec->F_Type_DPI2.rd, instr_dec->F_Type_DPI2.rs, instr_dec->F_Type_DPI2.subop2, instr_dec->F_Type_DPI2.shift, instr_dec->F_Type_DPI2.subop1, instr_dec->F_Type_DPI2.rm);
      break;
    case 33: // Instruction and3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_and3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 34: // Instruction eor3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_eor3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 35: // Instruction sub3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_sub3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 36: // Instruction rsb3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_rsb3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 37: // Instruction add3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_add3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 38: // Instruction adc3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_adc3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 39: // Instruction sbc3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_sbc3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 40: // Instruction rsc3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_rsc3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 41: // Instruction tst3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_tst3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 42: // Instruction teq3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_teq3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 43: // Instruction cmp3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_cmp3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 44: // Instruction cmn3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_cmn3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 45: // Instruction orr3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_orr3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 46: // Instruction mov3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_mov3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 47: // Instruction bic3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_bic3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 48: // Instruction mvn3
      ISA._behavior_arm_Type_DPI3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      ISA.behavior_mvn3(instr_dec->F_Type_DPI3.cond, instr_dec->F_Type_DPI3.op, instr_dec->F_Type_DPI3.func1, instr_dec->F_Type_DPI3.s, instr_dec->F_Type_DPI3.rn, instr_dec->F_Type_DPI3.rd, instr_dec->F_Type_DPI3.rotate, instr_dec->F_Type_DPI3.imm8);
      break;
    case 49: // Instruction mov4
      ISA._behavior_arm_Type_DPI4(instr_dec->F_Type_DPI4.cond, instr_dec->F_Type_DPI4.op, instr_dec->F_Type_DPI4.func1, instr_dec->F_Type_DPI4.s, instr_dec->F_Type_DPI4.imm4, instr_dec->F_Type_DPI4.rd, instr_dec->F_Type_DPI4.imm12);
      ISA.behavior_mov4(instr_dec->F_Type_DPI4.cond, instr_dec->F_Type_DPI4.op, instr_dec->F_Type_DPI4.func1, instr_dec->F_Type_DPI4.s, instr_dec->F_Type_DPI4.imm4, instr_dec->F_Type_DPI4.rd, instr_dec->F_Type_DPI4.imm12);
      break;
    case 50: // Instruction movt
      ISA._behavior_arm_Type_DPI4(instr_dec->F_Type_DPI4.cond, instr_dec->F_Type_DPI4.op, instr_dec->F_Type_DPI4.func1, instr_dec->F_Type_DPI4.s, instr_dec->F_Type_DPI4.imm4, instr_dec->F_Type_DPI4.rd, instr_dec->F_Type_DPI4.imm12);
      ISA.behavior_movt(instr_dec->F_Type_DPI4.cond, instr_dec->F_Type_DPI4.op, instr_dec->F_Type_DPI4.func1, instr_dec->F_Type_DPI4.s, instr_dec->F_Type_DPI4.imm4, instr_dec->F_Type_DPI4.rd, instr_dec->F_Type_DPI4.imm12);
      break;
    case 51: // Instruction nop
      ISA._behavior_arm_Type_DPI4(instr_dec->F_Type_DPI4.cond, instr_dec->F_Type_DPI4.op, instr_dec->F_Type_DPI4.func1, instr_dec->F_Type_DPI4.s, instr_dec->F_Type_DPI4.imm4, instr_dec->F_Type_DPI4.rd, instr_dec->F_Type_DPI4.imm12);
      ISA.behavior_nop(instr_dec->F_Type_DPI4.cond, instr_dec->F_Type_DPI4.op, instr_dec->F_Type_DPI4.func1, instr_dec->F_Type_DPI4.s, instr_dec->F_Type_DPI4.imm4, instr_dec->F_Type_DPI4.rd, instr_dec->F_Type_DPI4.imm12);
      break;
    case 52: // Instruction pkh
      ISA._behavior_arm_Type_DPI5(instr_dec->F_Type_DPI5.cond, instr_dec->F_Type_DPI5.op, instr_dec->F_Type_DPI5.func1, instr_dec->F_Type_DPI5.s, instr_dec->F_Type_DPI5.rn, instr_dec->F_Type_DPI5.rd, instr_dec->F_Type_DPI5.shiftamount, instr_dec->F_Type_DPI5.tb, instr_dec->F_Type_DPI5.subop1, instr_dec->F_Type_DPI5.rm);
      ISA.behavior_pkh(instr_dec->F_Type_DPI5.cond, instr_dec->F_Type_DPI5.op, instr_dec->F_Type_DPI5.func1, instr_dec->F_Type_DPI5.s, instr_dec->F_Type_DPI5.rn, instr_dec->F_Type_DPI5.rd, instr_dec->F_Type_DPI5.shiftamount, instr_dec->F_Type_DPI5.tb, instr_dec->F_Type_DPI5.subop1, instr_dec->F_Type_DPI5.rm);
      break;
    case 53: // Instruction bfi
      ISA._behavior_arm_Type_BTM1(instr_dec->F_Type_BTM1.cond, instr_dec->F_Type_BTM1.op, instr_dec->F_Type_BTM1.msb, instr_dec->F_Type_BTM1.rd, instr_dec->F_Type_BTM1.lsb, instr_dec->F_Type_BTM1.func1, instr_dec->F_Type_BTM1.rn);
      ISA.behavior_bfi(instr_dec->F_Type_BTM1.cond, instr_dec->F_Type_BTM1.op, instr_dec->F_Type_BTM1.msb, instr_dec->F_Type_BTM1.rd, instr_dec->F_Type_BTM1.lsb, instr_dec->F_Type_BTM1.func1, instr_dec->F_Type_BTM1.rn);
      break;
    case 54: // Instruction ubfx
      ISA._behavior_arm_Type_MED1(instr_dec->F_Type_MED1.cond, instr_dec->F_Type_MED1.op, instr_dec->F_Type_MED1.op1, instr_dec->F_Type_MED1.widthm1, instr_dec->F_Type_MED1.rd, instr_dec->F_Type_MED1.lsb, instr_dec->F_Type_MED1.op2, instr_dec->F_Type_MED1.rn);
      ISA.behavior_ubfx(instr_dec->F_Type_MED1.cond, instr_dec->F_Type_MED1.op, instr_dec->F_Type_MED1.op1, instr_dec->F_Type_MED1.widthm1, instr_dec->F_Type_MED1.rd, instr_dec->F_Type_MED1.lsb, instr_dec->F_Type_MED1.op2, instr_dec->F_Type_MED1.rn);
      break;
    case 55: // Instruction sbfx
      ISA._behavior_arm_Type_MED1(instr_dec->F_Type_MED1.cond, instr_dec->F_Type_MED1.op, instr_dec->F_Type_MED1.op1, instr_dec->F_Type_MED1.widthm1, instr_dec->F_Type_MED1.rd, instr_dec->F_Type_MED1.lsb, instr_dec->F_Type_MED1.op2, instr_dec->F_Type_MED1.rn);
      ISA.behavior_sbfx(instr_dec->F_Type_MED1.cond, instr_dec->F_Type_MED1.op, instr_dec->F_Type_MED1.op1, instr_dec->F_Type_MED1.widthm1, instr_dec->F_Type_MED1.rd, instr_dec->F_Type_MED1.lsb, instr_dec->F_Type_MED1.op2, instr_dec->F_Type_MED1.rn);
      break;
    case 56: // Instruction uxtb
      ISA._behavior_arm_Type_PCK1(instr_dec->F_Type_PCK1.cond, instr_dec->F_Type_PCK1.op1, instr_dec->F_Type_PCK1.func1, instr_dec->F_Type_PCK1.rn, instr_dec->F_Type_PCK1.rd, instr_dec->F_Type_PCK1.rotate, instr_dec->F_Type_PCK1.func2, instr_dec->F_Type_PCK1.rm);
      ISA.behavior_uxtb(instr_dec->F_Type_PCK1.cond, instr_dec->F_Type_PCK1.op1, instr_dec->F_Type_PCK1.func1, instr_dec->F_Type_PCK1.rn, instr_dec->F_Type_PCK1.rd, instr_dec->F_Type_PCK1.rotate, instr_dec->F_Type_PCK1.func2, instr_dec->F_Type_PCK1.rm);
      break;
    case 57: // Instruction uxth
      ISA._behavior_arm_Type_PCK1(instr_dec->F_Type_PCK1.cond, instr_dec->F_Type_PCK1.op1, instr_dec->F_Type_PCK1.func1, instr_dec->F_Type_PCK1.rn, instr_dec->F_Type_PCK1.rd, instr_dec->F_Type_PCK1.rotate, instr_dec->F_Type_PCK1.func2, instr_dec->F_Type_PCK1.rm);
      ISA.behavior_uxth(instr_dec->F_Type_PCK1.cond, instr_dec->F_Type_PCK1.op1, instr_dec->F_Type_PCK1.func1, instr_dec->F_Type_PCK1.rn, instr_dec->F_Type_PCK1.rd, instr_dec->F_Type_PCK1.rotate, instr_dec->F_Type_PCK1.func2, instr_dec->F_Type_PCK1.rm);
      break;
    case 58: // Instruction sxth
      ISA._behavior_arm_Type_PCK1(instr_dec->F_Type_PCK1.cond, instr_dec->F_Type_PCK1.op1, instr_dec->F_Type_PCK1.func1, instr_dec->F_Type_PCK1.rn, instr_dec->F_Type_PCK1.rd, instr_dec->F_Type_PCK1.rotate, instr_dec->F_Type_PCK1.func2, instr_dec->F_Type_PCK1.rm);
      ISA.behavior_sxth(instr_dec->F_Type_PCK1.cond, instr_dec->F_Type_PCK1.op1, instr_dec->F_Type_PCK1.func1, instr_dec->F_Type_PCK1.rn, instr_dec->F_Type_PCK1.rd, instr_dec->F_Type_PCK1.rotate, instr_dec->F_Type_PCK1.func2, instr_dec->F_Type_PCK1.rm);
      break;
    case 59: // Instruction rev
      ISA._behavior_arm_Type_PCK1(instr_dec->F_Type_PCK1.cond, instr_dec->F_Type_PCK1.op1, instr_dec->F_Type_PCK1.func1, instr_dec->F_Type_PCK1.rn, instr_dec->F_Type_PCK1.rd, instr_dec->F_Type_PCK1.rotate, instr_dec->F_Type_PCK1.func2, instr_dec->F_Type_PCK1.rm);
      ISA.behavior_rev(instr_dec->F_Type_PCK1.cond, instr_dec->F_Type_PCK1.op1, instr_dec->F_Type_PCK1.func1, instr_dec->F_Type_PCK1.rn, instr_dec->F_Type_PCK1.rd, instr_dec->F_Type_PCK1.rotate, instr_dec->F_Type_PCK1.func2, instr_dec->F_Type_PCK1.rm);
      break;
    case 60: // Instruction blx1
      ISA._behavior_arm_Type_BBLT(instr_dec->F_Type_BBLT.cond, instr_dec->F_Type_BBLT.op, instr_dec->F_Type_BBLT.h, instr_dec->F_Type_BBLT.offset);
      ISA.behavior_blx1(instr_dec->F_Type_BBLT.cond, instr_dec->F_Type_BBLT.op, instr_dec->F_Type_BBLT.h, instr_dec->F_Type_BBLT.offset);
      break;
    case 61: // Instruction b
      ISA._behavior_arm_Type_BBL(instr_dec->F_Type_BBL.cond, instr_dec->F_Type_BBL.op, instr_dec->F_Type_BBL.h, instr_dec->F_Type_BBL.offset);
      ISA.behavior_b(instr_dec->F_Type_BBL.cond, instr_dec->F_Type_BBL.op, instr_dec->F_Type_BBL.h, instr_dec->F_Type_BBL.offset);
      break;
    case 62: // Instruction bx
      ISA._behavior_arm_Type_MBXBLX(instr_dec->F_Type_MBXBLX.cond, instr_dec->F_Type_MBXBLX.op, instr_dec->F_Type_MBXBLX.func1, instr_dec->F_Type_MBXBLX.s, instr_dec->F_Type_MBXBLX.one1, instr_dec->F_Type_MBXBLX.one2, instr_dec->F_Type_MBXBLX.one3, instr_dec->F_Type_MBXBLX.subop2, instr_dec->F_Type_MBXBLX.func2, instr_dec->F_Type_MBXBLX.subop1, instr_dec->F_Type_MBXBLX.rm);
      ISA.behavior_bx(instr_dec->F_Type_MBXBLX.cond, instr_dec->F_Type_MBXBLX.op, instr_dec->F_Type_MBXBLX.func1, instr_dec->F_Type_MBXBLX.s, instr_dec->F_Type_MBXBLX.one1, instr_dec->F_Type_MBXBLX.one2, instr_dec->F_Type_MBXBLX.one3, instr_dec->F_Type_MBXBLX.subop2, instr_dec->F_Type_MBXBLX.func2, instr_dec->F_Type_MBXBLX.subop1, instr_dec->F_Type_MBXBLX.rm);
      break;
    case 63: // Instruction blx2
      ISA._behavior_arm_Type_MBXBLX(instr_dec->F_Type_MBXBLX.cond, instr_dec->F_Type_MBXBLX.op, instr_dec->F_Type_MBXBLX.func1, instr_dec->F_Type_MBXBLX.s, instr_dec->F_Type_MBXBLX.one1, instr_dec->F_Type_MBXBLX.one2, instr_dec->F_Type_MBXBLX.one3, instr_dec->F_Type_MBXBLX.subop2, instr_dec->F_Type_MBXBLX.func2, instr_dec->F_Type_MBXBLX.subop1, instr_dec->F_Type_MBXBLX.rm);
      ISA.behavior_blx2(instr_dec->F_Type_MBXBLX.cond, instr_dec->F_Type_MBXBLX.op, instr_dec->F_Type_MBXBLX.func1, instr_dec->F_Type_MBXBLX.s, instr_dec->F_Type_MBXBLX.one1, instr_dec->F_Type_MBXBLX.one2, instr_dec->F_Type_MBXBLX.one3, instr_dec->F_Type_MBXBLX.subop2, instr_dec->F_Type_MBXBLX.func2, instr_dec->F_Type_MBXBLX.subop1, instr_dec->F_Type_MBXBLX.rm);
      break;
    case 64: // Instruction swp
      ISA._behavior_arm_Type_MULT1(instr_dec->F_Type_MULT1.cond, instr_dec->F_Type_MULT1.op, instr_dec->F_Type_MULT1.func1, instr_dec->F_Type_MULT1.s, instr_dec->F_Type_MULT1.rn, instr_dec->F_Type_MULT1.rd, instr_dec->F_Type_MULT1.rs, instr_dec->F_Type_MULT1.subop2, instr_dec->F_Type_MULT1.func2, instr_dec->F_Type_MULT1.subop1, instr_dec->F_Type_MULT1.rm);
      ISA.behavior_swp(instr_dec->F_Type_MULT1.cond, instr_dec->F_Type_MULT1.op, instr_dec->F_Type_MULT1.func1, instr_dec->F_Type_MULT1.s, instr_dec->F_Type_MULT1.rn, instr_dec->F_Type_MULT1.rd, instr_dec->F_Type_MULT1.rs, instr_dec->F_Type_MULT1.subop2, instr_dec->F_Type_MULT1.func2, instr_dec->F_Type_MULT1.subop1, instr_dec->F_Type_MULT1.rm);
      break;
    case 65: // Instruction swpb
      ISA._behavior_arm_Type_MULT1(instr_dec->F_Type_MULT1.cond, instr_dec->F_Type_MULT1.op, instr_dec->F_Type_MULT1.func1, instr_dec->F_Type_MULT1.s, instr_dec->F_Type_MULT1.rn, instr_dec->F_Type_MULT1.rd, instr_dec->F_Type_MULT1.rs, instr_dec->F_Type_MULT1.subop2, instr_dec->F_Type_MULT1.func2, instr_dec->F_Type_MULT1.subop1, instr_dec->F_Type_MULT1.rm);
      ISA.behavior_swpb(instr_dec->F_Type_MULT1.cond, instr_dec->F_Type_MULT1.op, instr_dec->F_Type_MULT1.func1, instr_dec->F_Type_MULT1.s, instr_dec->F_Type_MULT1.rn, instr_dec->F_Type_MULT1.rd, instr_dec->F_Type_MULT1.rs, instr_dec->F_Type_MULT1.subop2, instr_dec->F_Type_MULT1.func2, instr_dec->F_Type_MULT1.subop1, instr_dec->F_Type_MULT1.rm);
      break;
    case 66: // Instruction mla
      ISA._behavior_arm_Type_MULT1(instr_dec->F_Type_MULT1.cond, instr_dec->F_Type_MULT1.op, instr_dec->F_Type_MULT1.func1, instr_dec->F_Type_MULT1.s, instr_dec->F_Type_MULT1.rn, instr_dec->F_Type_MULT1.rd, instr_dec->F_Type_MULT1.rs, instr_dec->F_Type_MULT1.subop2, instr_dec->F_Type_MULT1.func2, instr_dec->F_Type_MULT1.subop1, instr_dec->F_Type_MULT1.rm);
      ISA.behavior_mla(instr_dec->F_Type_MULT1.cond, instr_dec->F_Type_MULT1.op, instr_dec->F_Type_MULT1.func1, instr_dec->F_Type_MULT1.s, instr_dec->F_Type_MULT1.rn, instr_dec->F_Type_MULT1.rd, instr_dec->F_Type_MULT1.rs, instr_dec->F_Type_MULT1.subop2, instr_dec->F_Type_MULT1.func2, instr_dec->F_Type_MULT1.subop1, instr_dec->F_Type_MULT1.rm);
      break;
    case 67: // Instruction mul
      ISA._behavior_arm_Type_MULT1(instr_dec->F_Type_MULT1.cond, instr_dec->F_Type_MULT1.op, instr_dec->F_Type_MULT1.func1, instr_dec->F_Type_MULT1.s, instr_dec->F_Type_MULT1.rn, instr_dec->F_Type_MULT1.rd, instr_dec->F_Type_MULT1.rs, instr_dec->F_Type_MULT1.subop2, instr_dec->F_Type_MULT1.func2, instr_dec->F_Type_MULT1.subop1, instr_dec->F_Type_MULT1.rm);
      ISA.behavior_mul(instr_dec->F_Type_MULT1.cond, instr_dec->F_Type_MULT1.op, instr_dec->F_Type_MULT1.func1, instr_dec->F_Type_MULT1.s, instr_dec->F_Type_MULT1.rn, instr_dec->F_Type_MULT1.rd, instr_dec->F_Type_MULT1.rs, instr_dec->F_Type_MULT1.subop2, instr_dec->F_Type_MULT1.func2, instr_dec->F_Type_MULT1.subop1, instr_dec->F_Type_MULT1.rm);
      break;
    case 68: // Instruction mls
      ISA._behavior_arm_Type_MULT1(instr_dec->F_Type_MULT1.cond, instr_dec->F_Type_MULT1.op, instr_dec->F_Type_MULT1.func1, instr_dec->F_Type_MULT1.s, instr_dec->F_Type_MULT1.rn, instr_dec->F_Type_MULT1.rd, instr_dec->F_Type_MULT1.rs, instr_dec->F_Type_MULT1.subop2, instr_dec->F_Type_MULT1.func2, instr_dec->F_Type_MULT1.subop1, instr_dec->F_Type_MULT1.rm);
      ISA.behavior_mls(instr_dec->F_Type_MULT1.cond, instr_dec->F_Type_MULT1.op, instr_dec->F_Type_MULT1.func1, instr_dec->F_Type_MULT1.s, instr_dec->F_Type_MULT1.rn, instr_dec->F_Type_MULT1.rd, instr_dec->F_Type_MULT1.rs, instr_dec->F_Type_MULT1.subop2, instr_dec->F_Type_MULT1.func2, instr_dec->F_Type_MULT1.subop1, instr_dec->F_Type_MULT1.rm);
      break;
    case 69: // Instruction smlal
      ISA._behavior_arm_Type_MULT2(instr_dec->F_Type_MULT2.cond, instr_dec->F_Type_MULT2.op, instr_dec->F_Type_MULT2.func1, instr_dec->F_Type_MULT2.s, instr_dec->F_Type_MULT2.rdhi, instr_dec->F_Type_MULT2.rdlo, instr_dec->F_Type_MULT2.rs, instr_dec->F_Type_MULT2.subop2, instr_dec->F_Type_MULT2.func2, instr_dec->F_Type_MULT2.subop1, instr_dec->F_Type_MULT2.rm);
      ISA.behavior_smlal(instr_dec->F_Type_MULT2.cond, instr_dec->F_Type_MULT2.op, instr_dec->F_Type_MULT2.func1, instr_dec->F_Type_MULT2.s, instr_dec->F_Type_MULT2.rdhi, instr_dec->F_Type_MULT2.rdlo, instr_dec->F_Type_MULT2.rs, instr_dec->F_Type_MULT2.subop2, instr_dec->F_Type_MULT2.func2, instr_dec->F_Type_MULT2.subop1, instr_dec->F_Type_MULT2.rm);
      break;
    case 70: // Instruction smull
      ISA._behavior_arm_Type_MULT2(instr_dec->F_Type_MULT2.cond, instr_dec->F_Type_MULT2.op, instr_dec->F_Type_MULT2.func1, instr_dec->F_Type_MULT2.s, instr_dec->F_Type_MULT2.rdhi, instr_dec->F_Type_MULT2.rdlo, instr_dec->F_Type_MULT2.rs, instr_dec->F_Type_MULT2.subop2, instr_dec->F_Type_MULT2.func2, instr_dec->F_Type_MULT2.subop1, instr_dec->F_Type_MULT2.rm);
      ISA.behavior_smull(instr_dec->F_Type_MULT2.cond, instr_dec->F_Type_MULT2.op, instr_dec->F_Type_MULT2.func1, instr_dec->F_Type_MULT2.s, instr_dec->F_Type_MULT2.rdhi, instr_dec->F_Type_MULT2.rdlo, instr_dec->F_Type_MULT2.rs, instr_dec->F_Type_MULT2.subop2, instr_dec->F_Type_MULT2.func2, instr_dec->F_Type_MULT2.subop1, instr_dec->F_Type_MULT2.rm);
      break;
    case 71: // Instruction umlal
      ISA._behavior_arm_Type_MULT2(instr_dec->F_Type_MULT2.cond, instr_dec->F_Type_MULT2.op, instr_dec->F_Type_MULT2.func1, instr_dec->F_Type_MULT2.s, instr_dec->F_Type_MULT2.rdhi, instr_dec->F_Type_MULT2.rdlo, instr_dec->F_Type_MULT2.rs, instr_dec->F_Type_MULT2.subop2, instr_dec->F_Type_MULT2.func2, instr_dec->F_Type_MULT2.subop1, instr_dec->F_Type_MULT2.rm);
      ISA.behavior_umlal(instr_dec->F_Type_MULT2.cond, instr_dec->F_Type_MULT2.op, instr_dec->F_Type_MULT2.func1, instr_dec->F_Type_MULT2.s, instr_dec->F_Type_MULT2.rdhi, instr_dec->F_Type_MULT2.rdlo, instr_dec->F_Type_MULT2.rs, instr_dec->F_Type_MULT2.subop2, instr_dec->F_Type_MULT2.func2, instr_dec->F_Type_MULT2.subop1, instr_dec->F_Type_MULT2.rm);
      break;
    case 72: // Instruction umull
      ISA._behavior_arm_Type_MULT2(instr_dec->F_Type_MULT2.cond, instr_dec->F_Type_MULT2.op, instr_dec->F_Type_MULT2.func1, instr_dec->F_Type_MULT2.s, instr_dec->F_Type_MULT2.rdhi, instr_dec->F_Type_MULT2.rdlo, instr_dec->F_Type_MULT2.rs, instr_dec->F_Type_MULT2.subop2, instr_dec->F_Type_MULT2.func2, instr_dec->F_Type_MULT2.subop1, instr_dec->F_Type_MULT2.rm);
      ISA.behavior_umull(instr_dec->F_Type_MULT2.cond, instr_dec->F_Type_MULT2.op, instr_dec->F_Type_MULT2.func1, instr_dec->F_Type_MULT2.s, instr_dec->F_Type_MULT2.rdhi, instr_dec->F_Type_MULT2.rdlo, instr_dec->F_Type_MULT2.rs, instr_dec->F_Type_MULT2.subop2, instr_dec->F_Type_MULT2.func2, instr_dec->F_Type_MULT2.subop1, instr_dec->F_Type_MULT2.rm);
      break;
    case 73: // Instruction ldrt1
      ISA._behavior_arm_Type_LSI(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      ISA.behavior_ldrt1(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      break;
    case 74: // Instruction ldrbt1
      ISA._behavior_arm_Type_LSI(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      ISA.behavior_ldrbt1(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      break;
    case 75: // Instruction ldr1
      ISA._behavior_arm_Type_LSI(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      ISA.behavior_ldr1(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      break;
    case 76: // Instruction ldrb1
      ISA._behavior_arm_Type_LSI(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      ISA.behavior_ldrb1(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      break;
    case 77: // Instruction strt1
      ISA._behavior_arm_Type_LSI(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      ISA.behavior_strt1(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      break;
    case 78: // Instruction strbt1
      ISA._behavior_arm_Type_LSI(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      ISA.behavior_strbt1(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      break;
    case 79: // Instruction str1
      ISA._behavior_arm_Type_LSI(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      ISA.behavior_str1(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      break;
    case 80: // Instruction strb1
      ISA._behavior_arm_Type_LSI(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      ISA.behavior_strb1(instr_dec->F_Type_LSI.cond, instr_dec->F_Type_LSI.op, instr_dec->F_Type_LSI.p, instr_dec->F_Type_LSI.u, instr_dec->F_Type_LSI.b, instr_dec->F_Type_LSI.w, instr_dec->F_Type_LSI.l, instr_dec->F_Type_LSI.rn, instr_dec->F_Type_LSI.rd, instr_dec->F_Type_LSI.imm12);
      break;
    case 81: // Instruction ldrt2
      ISA._behavior_arm_Type_LSR(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      ISA.behavior_ldrt2(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      break;
    case 82: // Instruction ldrbt2
      ISA._behavior_arm_Type_LSR(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      ISA.behavior_ldrbt2(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      break;
    case 83: // Instruction ldr2
      ISA._behavior_arm_Type_LSR(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      ISA.behavior_ldr2(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      break;
    case 84: // Instruction ldrb2
      ISA._behavior_arm_Type_LSR(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      ISA.behavior_ldrb2(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      break;
    case 85: // Instruction strt2
      ISA._behavior_arm_Type_LSR(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      ISA.behavior_strt2(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      break;
    case 86: // Instruction strbt2
      ISA._behavior_arm_Type_LSR(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      ISA.behavior_strbt2(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      break;
    case 87: // Instruction str2
      ISA._behavior_arm_Type_LSR(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      ISA.behavior_str2(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      break;
    case 88: // Instruction strb2
      ISA._behavior_arm_Type_LSR(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      ISA.behavior_strb2(instr_dec->F_Type_LSR.cond, instr_dec->F_Type_LSR.op, instr_dec->F_Type_LSR.p, instr_dec->F_Type_LSR.u, instr_dec->F_Type_LSR.b, instr_dec->F_Type_LSR.w, instr_dec->F_Type_LSR.l, instr_dec->F_Type_LSR.rn, instr_dec->F_Type_LSR.rd, instr_dec->F_Type_LSR.shiftamount, instr_dec->F_Type_LSR.shift, instr_dec->F_Type_LSR.subop1, instr_dec->F_Type_LSR.rm);
      break;
    case 89: // Instruction ldrh
      ISA._behavior_arm_Type_LSE(instr_dec->F_Type_LSE.cond, instr_dec->F_Type_LSE.op, instr_dec->F_Type_LSE.p, instr_dec->F_Type_LSE.u, instr_dec->F_Type_LSE.i, instr_dec->F_Type_LSE.w, instr_dec->F_Type_LSE.l, instr_dec->F_Type_LSE.rn, instr_dec->F_Type_LSE.rd, instr_dec->F_Type_LSE.addr1, instr_dec->F_Type_LSE.subop2, instr_dec->F_Type_LSE.ss, instr_dec->F_Type_LSE.hh, instr_dec->F_Type_LSE.subop1, instr_dec->F_Type_LSE.addr2);
      ISA.behavior_ldrh(instr_dec->F_Type_LSE.cond, instr_dec->F_Type_LSE.op, instr_dec->F_Type_LSE.p, instr_dec->F_Type_LSE.u, instr_dec->F_Type_LSE.i, instr_dec->F_Type_LSE.w, instr_dec->F_Type_LSE.l, instr_dec->F_Type_LSE.rn, instr_dec->F_Type_LSE.rd, instr_dec->F_Type_LSE.addr1, instr_dec->F_Type_LSE.subop2, instr_dec->F_Type_LSE.ss, instr_dec->F_Type_LSE.hh, instr_dec->F_Type_LSE.subop1, instr_dec->F_Type_LSE.addr2);
      break;
    case 90: // Instruction ldrsb
      ISA._behavior_arm_Type_LSE(instr_dec->F_Type_LSE.cond, instr_dec->F_Type_LSE.op, instr_dec->F_Type_LSE.p, instr_dec->F_Type_LSE.u, instr_dec->F_Type_LSE.i, instr_dec->F_Type_LSE.w, instr_dec->F_Type_LSE.l, instr_dec->F_Type_LSE.rn, instr_dec->F_Type_LSE.rd, instr_dec->F_Type_LSE.addr1, instr_dec->F_Type_LSE.subop2, instr_dec->F_Type_LSE.ss, instr_dec->F_Type_LSE.hh, instr_dec->F_Type_LSE.subop1, instr_dec->F_Type_LSE.addr2);
      ISA.behavior_ldrsb(instr_dec->F_Type_LSE.cond, instr_dec->F_Type_LSE.op, instr_dec->F_Type_LSE.p, instr_dec->F_Type_LSE.u, instr_dec->F_Type_LSE.i, instr_dec->F_Type_LSE.w, instr_dec->F_Type_LSE.l, instr_dec->F_Type_LSE.rn, instr_dec->F_Type_LSE.rd, instr_dec->F_Type_LSE.addr1, instr_dec->F_Type_LSE.subop2, instr_dec->F_Type_LSE.ss, instr_dec->F_Type_LSE.hh, instr_dec->F_Type_LSE.subop1, instr_dec->F_Type_LSE.addr2);
      break;
    case 91: // Instruction ldrsh
      ISA._behavior_arm_Type_LSE(instr_dec->F_Type_LSE.cond, instr_dec->F_Type_LSE.op, instr_dec->F_Type_LSE.p, instr_dec->F_Type_LSE.u, instr_dec->F_Type_LSE.i, instr_dec->F_Type_LSE.w, instr_dec->F_Type_LSE.l, instr_dec->F_Type_LSE.rn, instr_dec->F_Type_LSE.rd, instr_dec->F_Type_LSE.addr1, instr_dec->F_Type_LSE.subop2, instr_dec->F_Type_LSE.ss, instr_dec->F_Type_LSE.hh, instr_dec->F_Type_LSE.subop1, instr_dec->F_Type_LSE.addr2);
      ISA.behavior_ldrsh(instr_dec->F_Type_LSE.cond, instr_dec->F_Type_LSE.op, instr_dec->F_Type_LSE.p, instr_dec->F_Type_LSE.u, instr_dec->F_Type_LSE.i, instr_dec->F_Type_LSE.w, instr_dec->F_Type_LSE.l, instr_dec->F_Type_LSE.rn, instr_dec->F_Type_LSE.rd, instr_dec->F_Type_LSE.addr1, instr_dec->F_Type_LSE.subop2, instr_dec->F_Type_LSE.ss, instr_dec->F_Type_LSE.hh, instr_dec->F_Type_LSE.subop1, instr_dec->F_Type_LSE.addr2);
      break;
    case 92: // Instruction strh
      ISA._behavior_arm_Type_LSE(instr_dec->F_Type_LSE.cond, instr_dec->F_Type_LSE.op, instr_dec->F_Type_LSE.p, instr_dec->F_Type_LSE.u, instr_dec->F_Type_LSE.i, instr_dec->F_Type_LSE.w, instr_dec->F_Type_LSE.l, instr_dec->F_Type_LSE.rn, instr_dec->F_Type_LSE.rd, instr_dec->F_Type_LSE.addr1, instr_dec->F_Type_LSE.subop2, instr_dec->F_Type_LSE.ss, instr_dec->F_Type_LSE.hh, instr_dec->F_Type_LSE.subop1, instr_dec->F_Type_LSE.addr2);
      ISA.behavior_strh(instr_dec->F_Type_LSE.cond, instr_dec->F_Type_LSE.op, instr_dec->F_Type_LSE.p, instr_dec->F_Type_LSE.u, instr_dec->F_Type_LSE.i, instr_dec->F_Type_LSE.w, instr_dec->F_Type_LSE.l, instr_dec->F_Type_LSE.rn, instr_dec->F_Type_LSE.rd, instr_dec->F_Type_LSE.addr1, instr_dec->F_Type_LSE.subop2, instr_dec->F_Type_LSE.ss, instr_dec->F_Type_LSE.hh, instr_dec->F_Type_LSE.subop1, instr_dec->F_Type_LSE.addr2);
      break;
    case 93: // Instruction ldrd
      ISA._behavior_arm_Type_LSE(instr_dec->F_Type_LSE.cond, instr_dec->F_Type_LSE.op, instr_dec->F_Type_LSE.p, instr_dec->F_Type_LSE.u, instr_dec->F_Type_LSE.i, instr_dec->F_Type_LSE.w, instr_dec->F_Type_LSE.l, instr_dec->F_Type_LSE.rn, instr_dec->F_Type_LSE.rd, instr_dec->F_Type_LSE.addr1, instr_dec->F_Type_LSE.subop2, instr_dec->F_Type_LSE.ss, instr_dec->F_Type_LSE.hh, instr_dec->F_Type_LSE.subop1, instr_dec->F_Type_LSE.addr2);
      ISA.behavior_ldrd(instr_dec->F_Type_LSE.cond, instr_dec->F_Type_LSE.op, instr_dec->F_Type_LSE.p, instr_dec->F_Type_LSE.u, instr_dec->F_Type_LSE.i, instr_dec->F_Type_LSE.w, instr_dec->F_Type_LSE.l, instr_dec->F_Type_LSE.rn, instr_dec->F_Type_LSE.rd, instr_dec->F_Type_LSE.addr1, instr_dec->F_Type_LSE.subop2, instr_dec->F_Type_LSE.ss, instr_dec->F_Type_LSE.hh, instr_dec->F_Type_LSE.subop1, instr_dec->F_Type_LSE.addr2);
      break;
    case 94: // Instruction strd
      ISA._behavior_arm_Type_LSE(instr_dec->F_Type_LSE.cond, instr_dec->F_Type_LSE.op, instr_dec->F_Type_LSE.p, instr_dec->F_Type_LSE.u, instr_dec->F_Type_LSE.i, instr_dec->F_Type_LSE.w, instr_dec->F_Type_LSE.l, instr_dec->F_Type_LSE.rn, instr_dec->F_Type_LSE.rd, instr_dec->F_Type_LSE.addr1, instr_dec->F_Type_LSE.subop2, instr_dec->F_Type_LSE.ss, instr_dec->F_Type_LSE.hh, instr_dec->F_Type_LSE.subop1, instr_dec->F_Type_LSE.addr2);
      ISA.behavior_strd(instr_dec->F_Type_LSE.cond, instr_dec->F_Type_LSE.op, instr_dec->F_Type_LSE.p, instr_dec->F_Type_LSE.u, instr_dec->F_Type_LSE.i, instr_dec->F_Type_LSE.w, instr_dec->F_Type_LSE.l, instr_dec->F_Type_LSE.rn, instr_dec->F_Type_LSE.rd, instr_dec->F_Type_LSE.addr1, instr_dec->F_Type_LSE.subop2, instr_dec->F_Type_LSE.ss, instr_dec->F_Type_LSE.hh, instr_dec->F_Type_LSE.subop1, instr_dec->F_Type_LSE.addr2);
      break;
    case 95: // Instruction ldm
      ISA._behavior_arm_Type_LSM(instr_dec->F_Type_LSM.cond, instr_dec->F_Type_LSM.op, instr_dec->F_Type_LSM.p, instr_dec->F_Type_LSM.u, instr_dec->F_Type_LSM.r, instr_dec->F_Type_LSM.w, instr_dec->F_Type_LSM.l, instr_dec->F_Type_LSM.rn, instr_dec->F_Type_LSM.rlist);
      ISA.behavior_ldm(instr_dec->F_Type_LSM.cond, instr_dec->F_Type_LSM.op, instr_dec->F_Type_LSM.p, instr_dec->F_Type_LSM.u, instr_dec->F_Type_LSM.r, instr_dec->F_Type_LSM.w, instr_dec->F_Type_LSM.l, instr_dec->F_Type_LSM.rn, instr_dec->F_Type_LSM.rlist);
      break;
    case 96: // Instruction stm
      ISA._behavior_arm_Type_LSM(instr_dec->F_Type_LSM.cond, instr_dec->F_Type_LSM.op, instr_dec->F_Type_LSM.p, instr_dec->F_Type_LSM.u, instr_dec->F_Type_LSM.r, instr_dec->F_Type_LSM.w, instr_dec->F_Type_LSM.l, instr_dec->F_Type_LSM.rn, instr_dec->F_Type_LSM.rlist);
      ISA.behavior_stm(instr_dec->F_Type_LSM.cond, instr_dec->F_Type_LSM.op, instr_dec->F_Type_LSM.p, instr_dec->F_Type_LSM.u, instr_dec->F_Type_LSM.r, instr_dec->F_Type_LSM.w, instr_dec->F_Type_LSM.l, instr_dec->F_Type_LSM.rn, instr_dec->F_Type_LSM.rlist);
      break;
    case 97: // Instruction strex
      ISA._behavior_arm_Type_MEMEX(instr_dec->F_Type_MEMEX.cond, instr_dec->F_Type_MEMEX.op, instr_dec->F_Type_MEMEX.s, instr_dec->F_Type_MEMEX.rn, instr_dec->F_Type_MEMEX.rd, instr_dec->F_Type_MEMEX.subop1, instr_dec->F_Type_MEMEX.func1, instr_dec->F_Type_MEMEX.rt);
      ISA.behavior_strex(instr_dec->F_Type_MEMEX.cond, instr_dec->F_Type_MEMEX.op, instr_dec->F_Type_MEMEX.s, instr_dec->F_Type_MEMEX.rn, instr_dec->F_Type_MEMEX.rd, instr_dec->F_Type_MEMEX.subop1, instr_dec->F_Type_MEMEX.func1, instr_dec->F_Type_MEMEX.rt);
      break;
    case 98: // Instruction ldrex
      ISA._behavior_arm_Type_MEMEX(instr_dec->F_Type_MEMEX.cond, instr_dec->F_Type_MEMEX.op, instr_dec->F_Type_MEMEX.s, instr_dec->F_Type_MEMEX.rn, instr_dec->F_Type_MEMEX.rd, instr_dec->F_Type_MEMEX.subop1, instr_dec->F_Type_MEMEX.func1, instr_dec->F_Type_MEMEX.rt);
      ISA.behavior_ldrex(instr_dec->F_Type_MEMEX.cond, instr_dec->F_Type_MEMEX.op, instr_dec->F_Type_MEMEX.s, instr_dec->F_Type_MEMEX.rn, instr_dec->F_Type_MEMEX.rd, instr_dec->F_Type_MEMEX.subop1, instr_dec->F_Type_MEMEX.func1, instr_dec->F_Type_MEMEX.rt);
      break;
    case 99: // Instruction cdp
      ISA._behavior_arm_Type_CDP(instr_dec->F_Type_CDP.cond, instr_dec->F_Type_CDP.op, instr_dec->F_Type_CDP.subop3, instr_dec->F_Type_CDP.funcc1, instr_dec->F_Type_CDP.crn, instr_dec->F_Type_CDP.crd, instr_dec->F_Type_CDP.cp_num, instr_dec->F_Type_CDP.funcc3, instr_dec->F_Type_CDP.subop1, instr_dec->F_Type_CDP.crm);
      ISA.behavior_cdp(instr_dec->F_Type_CDP.cond, instr_dec->F_Type_CDP.op, instr_dec->F_Type_CDP.subop3, instr_dec->F_Type_CDP.funcc1, instr_dec->F_Type_CDP.crn, instr_dec->F_Type_CDP.crd, instr_dec->F_Type_CDP.cp_num, instr_dec->F_Type_CDP.funcc3, instr_dec->F_Type_CDP.subop1, instr_dec->F_Type_CDP.crm);
      break;
    case 100: // Instruction mcr
      ISA._behavior_arm_Type_CRT(instr_dec->F_Type_CRT.cond, instr_dec->F_Type_CRT.op, instr_dec->F_Type_CRT.subop3, instr_dec->F_Type_CRT.funcc2, instr_dec->F_Type_CRT.l, instr_dec->F_Type_CRT.crn, instr_dec->F_Type_CRT.rd, instr_dec->F_Type_CRT.cp_num, instr_dec->F_Type_CRT.funcc3, instr_dec->F_Type_CRT.subop1, instr_dec->F_Type_CRT.crm);
      ISA.behavior_mcr(instr_dec->F_Type_CRT.cond, instr_dec->F_Type_CRT.op, instr_dec->F_Type_CRT.subop3, instr_dec->F_Type_CRT.funcc2, instr_dec->F_Type_CRT.l, instr_dec->F_Type_CRT.crn, instr_dec->F_Type_CRT.rd, instr_dec->F_Type_CRT.cp_num, instr_dec->F_Type_CRT.funcc3, instr_dec->F_Type_CRT.subop1, instr_dec->F_Type_CRT.crm);
      break;
    case 101: // Instruction mrc
      ISA._behavior_arm_Type_CRT(instr_dec->F_Type_CRT.cond, instr_dec->F_Type_CRT.op, instr_dec->F_Type_CRT.subop3, instr_dec->F_Type_CRT.funcc2, instr_dec->F_Type_CRT.l, instr_dec->F_Type_CRT.crn, instr_dec->F_Type_CRT.rd, instr_dec->F_Type_CRT.cp_num, instr_dec->F_Type_CRT.funcc3, instr_dec->F_Type_CRT.subop1, instr_dec->F_Type_CRT.crm);
      ISA.behavior_mrc(instr_dec->F_Type_CRT.cond, instr_dec->F_Type_CRT.op, instr_dec->F_Type_CRT.subop3, instr_dec->F_Type_CRT.funcc2, instr_dec->F_Type_CRT.l, instr_dec->F_Type_CRT.crn, instr_dec->F_Type_CRT.rd, instr_dec->F_Type_CRT.cp_num, instr_dec->F_Type_CRT.funcc3, instr_dec->F_Type_CRT.subop1, instr_dec->F_Type_CRT.crm);
      break;
    case 102: // Instruction ldc
      ISA._behavior_arm_Type_CLS(instr_dec->F_Type_CLS.cond, instr_dec->F_Type_CLS.op, instr_dec->F_Type_CLS.p, instr_dec->F_Type_CLS.u, instr_dec->F_Type_CLS.n, instr_dec->F_Type_CLS.w, instr_dec->F_Type_CLS.l, instr_dec->F_Type_CLS.rn, instr_dec->F_Type_CLS.crd, instr_dec->F_Type_CLS.cp_num, instr_dec->F_Type_CLS.imm8);
      ISA.behavior_ldc(instr_dec->F_Type_CLS.cond, instr_dec->F_Type_CLS.op, instr_dec->F_Type_CLS.p, instr_dec->F_Type_CLS.u, instr_dec->F_Type_CLS.n, instr_dec->F_Type_CLS.w, instr_dec->F_Type_CLS.l, instr_dec->F_Type_CLS.rn, instr_dec->F_Type_CLS.crd, instr_dec->F_Type_CLS.cp_num, instr_dec->F_Type_CLS.imm8);
      break;
    case 103: // Instruction stc
      ISA._behavior_arm_Type_CLS(instr_dec->F_Type_CLS.cond, instr_dec->F_Type_CLS.op, instr_dec->F_Type_CLS.p, instr_dec->F_Type_CLS.u, instr_dec->F_Type_CLS.n, instr_dec->F_Type_CLS.w, instr_dec->F_Type_CLS.l, instr_dec->F_Type_CLS.rn, instr_dec->F_Type_CLS.crd, instr_dec->F_Type_CLS.cp_num, instr_dec->F_Type_CLS.imm8);
      ISA.behavior_stc(instr_dec->F_Type_CLS.cond, instr_dec->F_Type_CLS.op, instr_dec->F_Type_CLS.p, instr_dec->F_Type_CLS.u, instr_dec->F_Type_CLS.n, instr_dec->F_Type_CLS.w, instr_dec->F_Type_CLS.l, instr_dec->F_Type_CLS.rn, instr_dec->F_Type_CLS.crd, instr_dec->F_Type_CLS.cp_num, instr_dec->F_Type_CLS.imm8);
      break;
    case 104: // Instruction bkpt
      ISA._behavior_arm_Type_MBKPT(instr_dec->F_Type_MBKPT.cond, instr_dec->F_Type_MBKPT.op, instr_dec->F_Type_MBKPT.func1, instr_dec->F_Type_MBKPT.s, instr_dec->F_Type_MBKPT.immediate, instr_dec->F_Type_MBKPT.subop2, instr_dec->F_Type_MBKPT.func2, instr_dec->F_Type_MBKPT.subop1, instr_dec->F_Type_MBKPT.rm);
      ISA.behavior_bkpt(instr_dec->F_Type_MBKPT.cond, instr_dec->F_Type_MBKPT.op, instr_dec->F_Type_MBKPT.func1, instr_dec->F_Type_MBKPT.s, instr_dec->F_Type_MBKPT.immediate, instr_dec->F_Type_MBKPT.subop2, instr_dec->F_Type_MBKPT.func2, instr_dec->F_Type_MBKPT.subop1, instr_dec->F_Type_MBKPT.rm);
      break;
    case 105: // Instruction swi
      ISA._behavior_arm_Type_MSWI(instr_dec->F_Type_MSWI.cond, instr_dec->F_Type_MSWI.op, instr_dec->F_Type_MSWI.subop3, instr_dec->F_Type_MSWI.swinumber);
      ISA.behavior_swi(instr_dec->F_Type_MSWI.cond, instr_dec->F_Type_MSWI.op, instr_dec->F_Type_MSWI.subop3, instr_dec->F_Type_MSWI.swinumber);
      break;
    case 106: // Instruction clz
      ISA._behavior_arm_Type_MCLZ(instr_dec->F_Type_MCLZ.cond, instr_dec->F_Type_MCLZ.op, instr_dec->F_Type_MCLZ.func1, instr_dec->F_Type_MCLZ.s, instr_dec->F_Type_MCLZ.one1, instr_dec->F_Type_MCLZ.rd, instr_dec->F_Type_MCLZ.one3, instr_dec->F_Type_MCLZ.subop2, instr_dec->F_Type_MCLZ.func2, instr_dec->F_Type_MCLZ.subop1, instr_dec->F_Type_MCLZ.rm);
      ISA.behavior_clz(instr_dec->F_Type_MCLZ.cond, instr_dec->F_Type_MCLZ.op, instr_dec->F_Type_MCLZ.func1, instr_dec->F_Type_MCLZ.s, instr_dec->F_Type_MCLZ.one1, instr_dec->F_Type_MCLZ.rd, instr_dec->F_Type_MCLZ.one3, instr_dec->F_Type_MCLZ.subop2, instr_dec->F_Type_MCLZ.func2, instr_dec->F_Type_MCLZ.subop1, instr_dec->F_Type_MCLZ.rm);
      break;
    case 107: // Instruction mrs
      ISA._behavior_arm_Type_MMSR1(instr_dec->F_Type_MMSR1.cond, instr_dec->F_Type_MMSR1.op, instr_dec->F_Type_MMSR1.func11, instr_dec->F_Type_MMSR1.r, instr_dec->F_Type_MMSR1.func12, instr_dec->F_Type_MMSR1.fieldmask, instr_dec->F_Type_MMSR1.rd, instr_dec->F_Type_MMSR1.zero3, instr_dec->F_Type_MMSR1.subop2, instr_dec->F_Type_MMSR1.func2, instr_dec->F_Type_MMSR1.subop1, instr_dec->F_Type_MMSR1.rm);
      ISA.behavior_mrs(instr_dec->F_Type_MMSR1.cond, instr_dec->F_Type_MMSR1.op, instr_dec->F_Type_MMSR1.func11, instr_dec->F_Type_MMSR1.r, instr_dec->F_Type_MMSR1.func12, instr_dec->F_Type_MMSR1.fieldmask, instr_dec->F_Type_MMSR1.rd, instr_dec->F_Type_MMSR1.zero3, instr_dec->F_Type_MMSR1.subop2, instr_dec->F_Type_MMSR1.func2, instr_dec->F_Type_MMSR1.subop1, instr_dec->F_Type_MMSR1.rm);
      break;
    case 108: // Instruction msr1
      ISA._behavior_arm_Type_MMSR1(instr_dec->F_Type_MMSR1.cond, instr_dec->F_Type_MMSR1.op, instr_dec->F_Type_MMSR1.func11, instr_dec->F_Type_MMSR1.r, instr_dec->F_Type_MMSR1.func12, instr_dec->F_Type_MMSR1.fieldmask, instr_dec->F_Type_MMSR1.rd, instr_dec->F_Type_MMSR1.zero3, instr_dec->F_Type_MMSR1.subop2, instr_dec->F_Type_MMSR1.func2, instr_dec->F_Type_MMSR1.subop1, instr_dec->F_Type_MMSR1.rm);
      ISA.behavior_msr1(instr_dec->F_Type_MMSR1.cond, instr_dec->F_Type_MMSR1.op, instr_dec->F_Type_MMSR1.func11, instr_dec->F_Type_MMSR1.r, instr_dec->F_Type_MMSR1.func12, instr_dec->F_Type_MMSR1.fieldmask, instr_dec->F_Type_MMSR1.rd, instr_dec->F_Type_MMSR1.zero3, instr_dec->F_Type_MMSR1.subop2, instr_dec->F_Type_MMSR1.func2, instr_dec->F_Type_MMSR1.subop1, instr_dec->F_Type_MMSR1.rm);
      break;
    case 109: // Instruction msr2
      ISA._behavior_arm_Type_MMSR2(instr_dec->F_Type_MMSR2.cond, instr_dec->F_Type_MMSR2.op, instr_dec->F_Type_MMSR2.func11, instr_dec->F_Type_MMSR2.r, instr_dec->F_Type_MMSR2.func12, instr_dec->F_Type_MMSR2.fieldmask, instr_dec->F_Type_MMSR2.one2, instr_dec->F_Type_MMSR2.rotate, instr_dec->F_Type_MMSR2.imm8);
      ISA.behavior_msr2(instr_dec->F_Type_MMSR2.cond, instr_dec->F_Type_MMSR2.op, instr_dec->F_Type_MMSR2.func11, instr_dec->F_Type_MMSR2.r, instr_dec->F_Type_MMSR2.func12, instr_dec->F_Type_MMSR2.fieldmask, instr_dec->F_Type_MMSR2.one2, instr_dec->F_Type_MMSR2.rotate, instr_dec->F_Type_MMSR2.imm8);
      break;
    case 110: // Instruction smc
      ISA._behavior_arm_Type_MSMC(instr_dec->F_Type_MSMC.cond, instr_dec->F_Type_MSMC.op, instr_dec->F_Type_MSMC.subop1, instr_dec->F_Type_MSMC.func1, instr_dec->F_Type_MSMC.func2, instr_dec->F_Type_MSMC.imm4);
      ISA.behavior_smc(instr_dec->F_Type_MSMC.cond, instr_dec->F_Type_MSMC.op, instr_dec->F_Type_MSMC.subop1, instr_dec->F_Type_MSMC.func1, instr_dec->F_Type_MSMC.func2, instr_dec->F_Type_MSMC.imm4);
      break;
    case 111: // Instruction dsmla
      ISA._behavior_arm_Type_DSPSM(instr_dec->F_Type_DSPSM.cond, instr_dec->F_Type_DSPSM.sm, instr_dec->F_Type_DSPSM.drd, instr_dec->F_Type_DSPSM.drn, instr_dec->F_Type_DSPSM.rs, instr_dec->F_Type_DSPSM.subop2, instr_dec->F_Type_DSPSM.yy, instr_dec->F_Type_DSPSM.xx, instr_dec->F_Type_DSPSM.subop1, instr_dec->F_Type_DSPSM.rm);
      ISA.behavior_dsmla(instr_dec->F_Type_DSPSM.cond, instr_dec->F_Type_DSPSM.sm, instr_dec->F_Type_DSPSM.drd, instr_dec->F_Type_DSPSM.drn, instr_dec->F_Type_DSPSM.rs, instr_dec->F_Type_DSPSM.subop2, instr_dec->F_Type_DSPSM.yy, instr_dec->F_Type_DSPSM.xx, instr_dec->F_Type_DSPSM.subop1, instr_dec->F_Type_DSPSM.rm);
      break;
    case 112: // Instruction dsmlal
      ISA._behavior_arm_Type_DSPSM(instr_dec->F_Type_DSPSM.cond, instr_dec->F_Type_DSPSM.sm, instr_dec->F_Type_DSPSM.drd, instr_dec->F_Type_DSPSM.drn, instr_dec->F_Type_DSPSM.rs, instr_dec->F_Type_DSPSM.subop2, instr_dec->F_Type_DSPSM.yy, instr_dec->F_Type_DSPSM.xx, instr_dec->F_Type_DSPSM.subop1, instr_dec->F_Type_DSPSM.rm);
      ISA.behavior_dsmlal(instr_dec->F_Type_DSPSM.cond, instr_dec->F_Type_DSPSM.sm, instr_dec->F_Type_DSPSM.drd, instr_dec->F_Type_DSPSM.drn, instr_dec->F_Type_DSPSM.rs, instr_dec->F_Type_DSPSM.subop2, instr_dec->F_Type_DSPSM.yy, instr_dec->F_Type_DSPSM.xx, instr_dec->F_Type_DSPSM.subop1, instr_dec->F_Type_DSPSM.rm);
      break;
    case 113: // Instruction dsmul
      ISA._behavior_arm_Type_DSPSM(instr_dec->F_Type_DSPSM.cond, instr_dec->F_Type_DSPSM.sm, instr_dec->F_Type_DSPSM.drd, instr_dec->F_Type_DSPSM.drn, instr_dec->F_Type_DSPSM.rs, instr_dec->F_Type_DSPSM.subop2, instr_dec->F_Type_DSPSM.yy, instr_dec->F_Type_DSPSM.xx, instr_dec->F_Type_DSPSM.subop1, instr_dec->F_Type_DSPSM.rm);
      ISA.behavior_dsmul(instr_dec->F_Type_DSPSM.cond, instr_dec->F_Type_DSPSM.sm, instr_dec->F_Type_DSPSM.drd, instr_dec->F_Type_DSPSM.drn, instr_dec->F_Type_DSPSM.rs, instr_dec->F_Type_DSPSM.subop2, instr_dec->F_Type_DSPSM.yy, instr_dec->F_Type_DSPSM.xx, instr_dec->F_Type_DSPSM.subop1, instr_dec->F_Type_DSPSM.rm);
      break;
    case 114: // Instruction dsmlaw
      ISA._behavior_arm_Type_DSPSM(instr_dec->F_Type_DSPSM.cond, instr_dec->F_Type_DSPSM.sm, instr_dec->F_Type_DSPSM.drd, instr_dec->F_Type_DSPSM.drn, instr_dec->F_Type_DSPSM.rs, instr_dec->F_Type_DSPSM.subop2, instr_dec->F_Type_DSPSM.yy, instr_dec->F_Type_DSPSM.xx, instr_dec->F_Type_DSPSM.subop1, instr_dec->F_Type_DSPSM.rm);
      ISA.behavior_dsmlaw(instr_dec->F_Type_DSPSM.cond, instr_dec->F_Type_DSPSM.sm, instr_dec->F_Type_DSPSM.drd, instr_dec->F_Type_DSPSM.drn, instr_dec->F_Type_DSPSM.rs, instr_dec->F_Type_DSPSM.subop2, instr_dec->F_Type_DSPSM.yy, instr_dec->F_Type_DSPSM.xx, instr_dec->F_Type_DSPSM.subop1, instr_dec->F_Type_DSPSM.rm);
      break;
    case 115: // Instruction dsmulw
      ISA._behavior_arm_Type_DSPSM(instr_dec->F_Type_DSPSM.cond, instr_dec->F_Type_DSPSM.sm, instr_dec->F_Type_DSPSM.drd, instr_dec->F_Type_DSPSM.drn, instr_dec->F_Type_DSPSM.rs, instr_dec->F_Type_DSPSM.subop2, instr_dec->F_Type_DSPSM.yy, instr_dec->F_Type_DSPSM.xx, instr_dec->F_Type_DSPSM.subop1, instr_dec->F_Type_DSPSM.rm);
      ISA.behavior_dsmulw(instr_dec->F_Type_DSPSM.cond, instr_dec->F_Type_DSPSM.sm, instr_dec->F_Type_DSPSM.drd, instr_dec->F_Type_DSPSM.drn, instr_dec->F_Type_DSPSM.rs, instr_dec->F_Type_DSPSM.subop2, instr_dec->F_Type_DSPSM.yy, instr_dec->F_Type_DSPSM.xx, instr_dec->F_Type_DSPSM.subop1, instr_dec->F_Type_DSPSM.rm);
      break;
    } // switch (ins_id)
    if (!ac_wait_sig) ac_instr_counter++;
//!Updating Regs for behavioral simulation.
    if (instr_in_batch < instr_batch_size) {
      instr_in_batch++;
    }
    else {
      instr_in_batch = 0;
      wait(1, SC_NS);
    }
  } // for (;;)
} // behavior()


#include <ac_sighandlers.H>

void arm::init() {
  set_args(ac_argc, ac_argv);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();

  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
#ifndef AC_COMPSIM
  set_running();
#else
  void Execute(int argc, char *argv[]);
  Execute(argc, argv);
#endif
}

void arm::init(int ac, char *av[]) {
  extern char* appfilename;
  set_args(ac_argc, ac_argv);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();

  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
#ifndef AC_COMPSIM
  set_running();
#else
  void Execute(int argc, char *argv[]);
  Execute(argc, argv);
#endif
}

//Stop simulation (may receive exit status)
void arm::stop(int status) {
  cerr << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
#ifndef AC_COMPSIM
  set_stopped();
#endif
  longjmp(ac_env, 2);
}

void arm::load(char* program) {
  APP_MEM->load(program);
}

void arm::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns pointer to gdbstub
AC_GDB<arm_parms::ac_word>* arm::get_gdbstub() {
  return gdbstub;
}

// Returns true if model endianness doesn't match with host's, false otherwise
bool arm::get_ac_tgt_endian() {
  return ac_tgt_endian;
}

// Stops the processor
void arm::ac_stop() {
  stop();
}

// Returns ac_pc value
unsigned arm::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void arm::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void arm::PrintStat() {
  ac_arch<arm_parms::ac_word, arm_parms::ac_Hword>::PrintStat();
}

// Enables GDB
void arm::enable_gdb(int port) {
  gdbstub->set_port(port);
  gdbstub->enable();
  gdbstub->connect();
}

